### ISSUE TITLE
PGP support

### ISSUE THREAD

**Issue by ifuchs** [holzschu/a-shell#348]
Could the gnupgp commands be added to A-shell?

**Comment by holzschu** [comment]
I would rather avoid anything covered by the GNU GPL, as the position of the FSF is that the GPL is incompatible with distribution on the AppStore.

**Comment by MidnightRocket** [comment]
I have recently setup PGP signing on WorkingCopy, and was looking at the resulting git commit object, when I found that WorkingCopy uses a PGP library written in Objective C, called [ObjectivePGP](https://objectivepgp.com)

I thought that this could maybe be a solution?  
I realize that this may not be a high priority for many people though 😅  

I also realize that a full fledged gpg mimicking cli, using [ObjectivePGP](https://objectivepgp.com) requires more effort than what's worth. But maybe a bare bones implementation, just to get git signed commits/tags working could be of interest for some.

**Comment by jakirkham** [comment]
Another option might be signing with an SSH key. IIUC this would be possible once issue ( https://github.com/libgit2/libgit2/issues/6397 ) is resolved

**Comment by holzschu** [comment]
So, we still don't have PGP support, but we recently added the commands `age` for encryption and `minisign` for signing and verifying files. Both are available with `pkg install`.
