### ISSUE TITLE
Perl broken in 215

### ISSUE THREAD

**Issue by normen** [holzschu/a-shell#374]
It seems like I can't run Perl scripts anymore in the latest version:

```
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /var/mobile/Containers/Data/Application/201ED9FE
-05C0-4690-996E-440A9D9C06D0/Documents/perl5/lib/perl5 /private/var/containers/Bundle/Application/F9A869EA-5556-4139-9455-C42AEEA1CD82/a-Sh
ell.app/Perl) at .normen/install.pl line 2.
BEGIN failed--compilation aborted at .normen/install.pl line 2.
```

**Comment by holzschu** [comment]
I think I see the problem. Can you send me the result of `env | grep PERL`?

**Comment by normen** [comment]
```
PATH=/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/perl5/bin:/private/var/containers/Bundle/Applic
ation/9B97FA4C-BF99-4184-8EAA-B03054551499/a-Shell.app/bin:/private/var/containers/Bundle/Application/9B97FA4C-BF99-4184-8EAA-B03054551499/
a-Shell.app/Library/bin:/private/var/containers/Bundle/Application/9B97FA4C-BF99-4184-8EAA-B03054551499/a-Shell.app/Library/bin3:/var/mobil
e/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Library/bin:/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8
E9F-A410DDD9C138/Documents/bin:/usr/bin:/bin:/usr/sbin:/sbin::/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410D
DD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.norme
n/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell::/private/
var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Da
ta/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-
D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell::/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9
C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/b
in/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/
mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/A
pplication/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673
-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell::/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138
/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a
-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobi
le/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Appli
cation/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-406
1-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Docu
ments/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shel
l:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Co
ntainers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Applicatio
n/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/.normen/bin/a-shell:/private/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9
F-A410DDD9C138/Documents/.normen/bin/a-shell
MANPATH=/private/var/containers/Bundle/Application/9B97FA4C-BF99-4184-8EAA-B03054551499/a-Shell.app/man:/var/mobile/Containers/Data/Applica
tion/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Library/man:/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Document
s/perl5/man
PERL5LIB=/var/mobile/Containers/Data/Application/201ED9FE-05C0-4690-996E-440A9D9C06D0/Documents/perl5/lib/perl5:/private/var/containers/Bun
dle/Application/F9A869EA-5556-4139-9455-C42AEEA1CD82/a-Shell.app/Perl
PERL_LOCAL_LIB_ROOT=/var/mobile/Containers/Data/Application/BA2E6EB4-D673-4061-8E9F-A410DDD9C138/Documents/perl5
PERL_MB_OPT=--install_base "/var/mobile/Containers/Data/Application/201ED9FE-05C0-4690-996E-440A9D9C06D0/Documents/perl5"
```

**Comment by normen** [comment]
Oh, its actually my local perl5 install.. Theres some perl versions of command line tools that seemed to have interfered..

Still it would be awesome if the amount of perl interpreters could be increased, I think thats why cpan messed up my install..

**Comment by holzschu** [comment]
So, `PERL5LIB` and `PERL_MB_OPT` are definitely my fault, and will be fixed in the next build. I'm not certain about the 20 or so `$HOME/Documents/.normen/bin/a-shell` at the end of the `PATH`. They could be coming from my side, but I don't see how.

While waiting for the next build, you can change `PERL5LIB` and `PERL_MB_OPT` to get Perl working:
```
setenv PERL5LIB $HOME/Documents/perl5/lib/perl5:$APPDIR/Perl
setenv PERL_MB_OPT --install_base $HOME/perl5/
```
(the last one may require quotes around `--install_base $HOME/perl5/`)

**Comment by normen** [comment]
It is a line in my .profile, seems like its read a few times..
.profile:
```
export NORMEN=$HOME/Documents/.normen
export PATH=$PATH:$NORMEN/bin/a-shell
alias git git.pl
```

**Comment by normen** [comment]
For some reason `help -l` doesn't seem to work either..

**Comment by holzschu** [comment]
I don't know about `help -l`, but it seems that preserving the `PATH` needs to ensure that I'm not adding a directory that is already in the `PATH`. I've fixed that.

**Comment by normen** [comment]
Things seem to be halfway normal after adding the suggested options to my `.profile`, I did have to add the quotes.

```
cpan -Ti App::Music::ChordPro
cpan -Ti Graph::Easy
```

Work again and the apps install but I still get the error message about  `-T` at the end of the install, and I always have to specify `-Ti`: 
```
>(error): Could not expand [-T]. Check the module name.
>(info): I can suggest names if you install one of Text::Levenshtein::XS, Text::Levenshtein::Damerau::XS, Text::Levenshtein, and Text::Leve
nshtein::Damerau::PP
>(info): and you provide the -x option on invocation.
>(error): Skipping -T because I couldn't find a matching namespace.
```

**Comment by holzschu** [comment]
Build 216 is out now, and it should fix the `Can't locate strict.pm in @INC` issues. You should be able to remove the `PERL` variables from your `.profile`.

**Comment by normen** [comment]
Yes, looks like the path issues are gone. `help -l` seems to work as well, can't reproduce the situation where it didn't show anything. Maybe it was something with the paths as well.

Still have the "phantom parameter" issue where cpan complains about `[-T]` being in the list of libraries to install and I have to specify `-Ti` when using cpan. I removed all local folders from a-shell and only used `cpan` to install the apps mentioned above so there shouldn't be any local specialties on my side.

**Comment by holzschu** [comment]
For the phantom parameter: I set `CPAN_OPTS` to `-T` to disable tests. But it can be interfering with your own setup. Maybe you could call `unsetenv CPAN_OPTS` in your `.profile` to clear the variable.

**Comment by normen** [comment]
Right, that seems to make `cpan -Ti` work like normal, except for native builds, as expected. Still don't know what could cause this if it doesn't happen for you as I only use cpan to install two apps. I guess when cpan sets up the local perl folders and settings something goes wrong.
